// Renderer code strings for each template.
// Kept in a separate file to avoid nesting backtick template literals.

const CODECRAFT_RENDERER = [
  "const [activeTab, setActiveTab] = React.useState('about');",
  "return (",
  '  <div className="min-h-screen text-gray-100 p4 sm:p-8 flex flex-col justify-between" style={{backgroundColor: \'var(--bg)\'}}>',
  '    <header className="max-w-4xl mx-auto w-full border border-white/5 rounded-lg overflow-hidden shadow-2xl mb-8 bg-white/[0.02]">',
  '      <div className="bg-gray-900 px-4 py-3 border-b border-gray-800 flex items-center justify-between">',
  '        <div className="flex space-x-2">',
  '          <span className="w-3 h-3 rounded-full bg-red-500"></span>',
  '          <span className="w-3 h-3 rounded-full bg-yellow-500"></span>',
  '          <span className="w-3 h-3 rounded-full bg-green-500"></span>',
  '        </div>',
  '        <span className="text-xs text-gray-400 font-mono flex items-center"><Terminal size={12} className="mr-1" style={{color:\'var(--accent)\'}} /> portfolio_shell</span>',
  '        <div className="w-12"></div>',
  '      </div>',
  '      <div className="p-6 sm:p-8 font-mono">',
  '        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">',
  '          <div>',
  "            <p className=\"text-gray-400 text-sm\"># Welcome to the shell of</p>",
  "            <h1 className=\"text-3xl sm:text-4xl font-extrabold mt-1\" style={{ color: 'var(--primary)' }}>{personalInfo.fullName || 'John Doe'}</h1>",
  "            <p className=\"text-sm mt-1\" style={{color: 'var(--accent)'}}>~/ {personalInfo.location || 'San Francisco, CA'}</p>",
  '          </div>',
  '          {personalInfo.avatarUrl && <img src={personalInfo.avatarUrl} alt="Avatar" className="w-20 h-20 rounded-full border border-gray-700 object-cover" />}',
  '        </div>',
  '        <p className="mt-4 text-gray-300 leading-relaxed text-sm max-w-2xl">{personalInfo.bio}</p>',
  '      </div>',
  '    </header>',
  '    <main className="max-w-4xl mx-auto w-full flex-grow">',
  '      <div className="flex border-b border-gray-800 mb-6 font-mono overflow-x-auto">',
  "        {sectionsOrder.map((section) => (<button key={section} onClick={() => setActiveTab(section)} className={`px-4 py-2 text-sm capitalize whitespace-nowrap ${activeTab === section ? 'border-b-2 text-white' : 'text-gray-400 hover:text-white'}`} style={{borderColor: activeTab === section ? 'var(--primary)' : 'transparent', color: activeTab === section ? 'var(--primary)' : undefined}}>{section}</button>))}",
  '      </div>',
  '      <div className="font-mono space-y-6">',
  "        {activeTab === 'hero' && (<div className=\"p-6 border border-white/5 rounded-lg bg-white/[0.01]\"><h2 className=\"text-xl font-bold flex items-center\" style={{color:'var(--accent)'}}><Code size={18} className=\"mr-2\" /> $ cat welcome.sh</h2><pre className=\"text-xs text-blue-400 mt-4 overflow-x-auto\">const dev = {JSON.stringify({name: personalInfo.fullName, email: personalInfo.email, socials}, null, 2)}</pre></div>)}",
  "        {activeTab === 'about' && (<div className=\"p-6 border border-white/5 rounded-lg bg-white/[0.01] space-y-4\"><h2 className=\"text-xl font-bold flex items-center\" style={{color:'var(--accent)'}}><Cpu size={18} className=\"mr-2\" /> $ cat about_me.txt</h2><p className=\"text-gray-300 text-sm leading-relaxed\">{personalInfo.bio}</p>{education?.length > 0 && (<div className=\"mt-6\"><h3 className=\"text-lg font-bold text-white mb-3 flex items-center\"><GraduationCap size={16} className=\"mr-2\" style={{color: 'var(--primary)'}} /> Education</h3>{education.map((edu, idx) => (<div key={idx} className=\"border-l-2 border-gray-800 pl-4 py-1 mb-3\"><h4 className=\"text-sm font-semibold text-white\">{edu.degree}</h4><p className=\"text-xs text-gray-400\">{edu.college} ({edu.year})</p></div>))}</div>)}</div>)}",
  "        {activeTab === 'skills' && (<div className=\"p-6 border border-white/5 rounded-lg bg-white/[0.01]\"><h2 className=\"text-xl font-bold flex items-center mb-4\" style={{color:'var(--accent)'}}><Terminal size={18} className=\"mr-2\" /> $ ls -la skills/</h2><div className=\"grid grid-cols-1 sm:grid-cols-2 gap-4\">{skills.map((skill, idx) => (<div key={idx} className=\"bg-gray-950 p-3 rounded border border-gray-900\"><div className=\"flex justify-between items-center text-xs mb-1\"><span className=\"text-white\">{skill.name}</span><span className=\"text-gray-400\">{skill.level}/5</span></div><div className=\"w-full bg-gray-800 h-1.5 rounded overflow-hidden\"><div className=\"h-full\" style={{ width: `${(skill.level / 5) * 100}%`, backgroundColor: 'var(--primary)' }}></div></div></div>))}</div></div>)}",
  "        {activeTab === 'projects' && (<div className=\"space-y-4\"><h2 className=\"text-xl font-bold flex items-center px-2\" style={{color:'var(--accent)'}}><FolderGit2 size={18} className=\"mr-2\" /> $ git log --projects</h2><div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">{projects.map((proj, idx) => (<div key={idx} className=\"p-6 border border-white/5 rounded-lg bg-white/[0.01] flex flex-col justify-between\"><div><h3 className=\"text-lg font-bold text-white mb-2\">{proj.title}</h3><p className=\"text-xs text-gray-400 mb-4\">{proj.description}</p></div><div className=\"flex space-x-3 text-xs\">{proj.githubLink && <a href={proj.githubLink} className=\"text-gray-400 hover:text-white\">Github</a>}{proj.liveLink && <a href={proj.liveLink} className=\"hover:underline\" style={{color: 'var(--primary)'}}>Live</a>}</div></div>))}</div></div>)}",
  "        {activeTab === 'experience' && (<div className=\"p-6 border border-white/5 rounded-lg bg-white/[0.01] space-y-4\"><h2 className=\"text-xl font-bold flex items-center mb-4\" style={{color:'var(--accent)'}}><Calendar size={18} className=\"mr-2\" /> $ cat work_history.json</h2>{experience.map((exp, idx) => (<div key={idx} className=\"relative pl-6 border-l-2 border-gray-800 mb-4\"><span className=\"absolute left-[-5px] top-1.5 w-2 h-2 rounded-full\" style={{ backgroundColor: 'var(--primary)' }}></span><div className=\"flex justify-between items-center text-xs\"><h3 className=\"font-bold text-white\">{exp.role}</h3><span className=\"text-gray-400\">{exp.duration}</span></div><h4 className=\"text-xs mt-0.5\" style={{color: 'var(--accent)'}}>{exp.company}</h4><p className=\"text-xs text-gray-400 mt-2\">{exp.description}</p></div>))}</div>)}",
  "        {activeTab === 'contact' && (<div className=\"p-6 border border-white/5 rounded-lg bg-white/[0.01] space-y-4\"><h2 className=\"text-xl font-bold flex items-center\" style={{color:'var(--accent)'}}><Mail size={18} className=\"mr-2\" /> $ mail -s &quot;hello&quot;</h2><p className=\"text-sm text-gray-300\">Email: <a href={`mailto:${personalInfo.email}`} style={{color: 'var(--primary)'}}>{personalInfo.email}</a></p></div>)}",
  '      </div>',
  '    </main>',
  '  </div>',
  ');',
].join('\n');

const DEVHUB_RENDERER = [
  'return (',
  '  <div className="min-h-screen text-gray-100" style={{backgroundColor: \'var(--bg)\'}}>',
  '    <nav className="border-b border-gray-800 bg-gray-950/80 backdrop-blur sticky top-0 z-50">',
  '      <div className="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center">',
  "        <span className=\"text-lg font-bold\" style={{color:'var(--primary)'}}>{personalInfo.fullName?.split(' ')[0]}.</span>",
  '        <div className="flex space-x-6 text-sm">',
  '          {sectionsOrder.map((section) => (<a key={section} href={`#${section}`} className="text-gray-400 hover:text-white capitalize">{section}</a>))}',
  '        </div>',
  '      </div>',
  '    </nav>',
  '    <div className="max-w-6xl mx-auto px-4 py-12 space-y-20">',
  '      {sectionsOrder.map((section) => {',
  "        if (section === 'hero') { return (<section key=\"hero\" id=\"hero\" className=\"flex flex-col-reverse md:flex-row items-center justify-between gap-8 py-8\"><div className=\"max-w-2xl space-y-6\"><h1 className=\"text-4xl sm:text-6xl font-extrabold\">Hi, I'm <span style={{color: 'var(--primary)'}}>{personalInfo.fullName}</span></h1><p className=\"text-lg text-gray-400 leading-relaxed\">{personalInfo.bio}</p><a href=\"#contact\" className=\"px-6 py-3 font-semibold text-sm text-white rounded transition text-center inline-block\" style={{backgroundColor: 'var(--primary)', borderRadius: 'var(--radius)'}}>Contact Me</a></div>{personalInfo.avatarUrl && (<div className=\"w-48 h-48 md:w-64 md:h-64 rounded-full overflow-hidden border-4 shadow-xl shrink-0\" style={{borderColor: 'var(--primary)'}}><img src={personalInfo.avatarUrl} alt={personalInfo.fullName} className=\"w-full h-full object-cover\" /></div>)}</section>); }",
  "        if (section === 'projects') { return (<section key=\"projects\" id=\"projects\" className=\"space-y-6 scroll-mt-20\"><h2 className=\"text-2xl font-bold border-b border-gray-800 pb-2\">Projects</h2><div className=\"grid grid-cols-1 md:grid-cols-3 gap-6\">{projects.map((proj, i) => (<div key={i} className=\"p-6 bg-slate-900/40 border border-white/5 flex flex-col justify-between\" style={{borderRadius: 'var(--radius)'}}><div><h3 className=\"text-lg font-bold text-white mb-2\">{proj.title}</h3><p className=\"text-xs text-gray-400 mb-4\">{proj.description}</p></div><div className=\"flex space-x-4 text-xs font-semibold pt-2 border-t border-gray-800\">{proj.githubLink && <a href={proj.githubLink} className=\"text-gray-400 hover:text-white\">Code</a>}{proj.liveLink && <a href={proj.liveLink} className=\"hover:underline\" style={{color: 'var(--primary)'}}>Live</a>}</div></div>))}</div></section>); }",
  "        if (section === 'skills') { return (<section key=\"skills\" id=\"skills\" className=\"space-y-6 scroll-mt-20\"><h2 className=\"text-2xl font-bold border-b border-gray-800 pb-2\">Technical Stack</h2><div className=\"grid grid-cols-2 sm:grid-cols-4 gap-4\">{skills.map((skill, i) => (<div key={i} className=\"p-4 bg-slate-900/40 border border-white/5 flex flex-col justify-between\" style={{borderRadius: 'var(--radius)'}}><span className=\"font-bold text-sm text-white mb-2\">{skill.name}</span><span className=\"text-xs font-semibold\" style={{color: 'var(--primary)'}}>{skill.level}/5</span></div>))}</div></section>); }",
  '        return null;',
  '      })}',
  '    </div>',
  '  </div>',
  ');',
].join('\n');

const VIVEPORTFOLIO_RENDERER = [
  "const [typedText, setTypedText] = React.useState('');",
  'React.useEffect(() => {',
  "  const roles = ['Software Developer', 'Full Stack Developer', 'Problem Solver', 'CyberSecurity Enthusiast'];",
  '  let roleIdx = 0; let charIdx = 0; let isDeleting = false; let timer;',
  '  const tick = () => {',
  '    const currentRole = roles[roleIdx];',
  '    if (!isDeleting) {',
  '      setTypedText(currentRole.substring(0, charIdx + 1)); charIdx++;',
  '      if (charIdx === currentRole.length) { isDeleting = true; timer = setTimeout(tick, 1500); }',
  '      else { timer = setTimeout(tick, 100); }',
  '    } else {',
  '      setTypedText(currentRole.substring(0, charIdx - 1)); charIdx--;',
  '      if (charIdx === 0) { isDeleting = false; roleIdx = (roleIdx + 1) % roles.length; timer = setTimeout(tick, 500); }',
  '      else { timer = setTimeout(tick, 50); }',
  '    }',
  '  };',
  '  timer = setTimeout(tick, 500);',
  '  return () => clearTimeout(timer);',
  '}, []);',
  "const initials = personalInfo.fullName ? personalInfo.fullName.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2) : 'PF';",
  'return (',
  '  <div className="min-h-screen text-[#1a1a1a] bg-[#f8f7f4] font-sans relative">',
  '    <style>{`.grid-overlay-vp{position:absolute;inset:0;background-image:linear-gradient(#ddd9d1 1px,transparent 1px),linear-gradient(90deg,#ddd9d1 1px,transparent 1px);background-size:48px 48px;opacity:0.35}.vp-card{background:#ffffff;border:1px solid #ddd9d1;border-radius:12px;transition:all 0.25s}.vp-card:hover{border-color:#c8502a;box-shadow:0 4px 20px rgba(200,80,42,0.08)}.vp-accent-text{color:#c8502a}.vp-timeline::before{content:\'\';position:absolute;left:14px;top:0;bottom:0;width:1.5px;background:#ddd9d1}.vp-project-card::before{content:\'\';position:absolute;top:0;left:0;width:4px;height:100%;background:#c8502a;transform:scaleY(0);transform-origin:bottom;transition:transform 0.3s ease}.vp-project-card:hover::before{transform:scaleY(1)}`}</style>',
  '    <nav className="fixed top-0 w-full z-40 bg-[#f8f7f4]/90 backdrop-blur border-b border-[#ddd9d1] py-3.5 px-6">',
  '      <div className="max-w-5xl mx-auto flex justify-between items-center w-full">',
  '        <span className="font-mono font-bold text-sm">&lt;{initials} /&gt;</span>',
  '        <div className="flex space-x-6 text-[13px] font-semibold text-[#4a4a4a]">',
  '          <a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a>',
  '          <a href="#skills" className="font-bold vp-accent-text">Skills</a><a href="#contact">Contact</a>',
  '        </div>',
  '      </div>',
  '    </nav>',
  '    <section id="home" className="min-h-screen bg-white relative overflow-hidden flex items-center pt-16">',
  '      <div className="grid-overlay-vp"></div>',
  '      <div className="max-w-5xl mx-auto w-full px-6 py-16 grid grid-cols-1 md:grid-cols-12 gap-8 items-center relative z-10">',
  '        <div className="md:col-span-7 space-y-6">',
  '          <p className="font-mono text-xs uppercase tracking-wider vp-accent-text font-bold flex items-center space-x-2"><Code size={14} /> <span>Hello World, I\'m</span></p>',
  "          <h1 className=\"text-4xl sm:text-5xl font-extrabold tracking-tight text-[#1a1a1a] leading-none\">{personalInfo.fullName ? personalInfo.fullName.split(' ')[0] : 'Jon'}<br /><span className=\"vp-accent-text\">{personalInfo.fullName ? personalInfo.fullName.split(' ').slice(1).join(' ') : 'Doe'}</span></h1>",
  '          <div className="font-mono text-[13px] text-[#8a8a8a] bg-[#f0ede8] border-l-[3px] border-[#c8502a] inline-block px-3.5 py-2 rounded-md"><span className="text-[#4a4a4a]">const role = </span><span className="text-black font-semibold">"{typedText}"</span><span className="vp-accent-text font-bold animate-pulse">|</span></div>',
  '          <p className="text-[#4a4a4a] text-sm leading-relaxed">{personalInfo.bio}</p>',
  '          <div className="flex space-x-6 pt-4 border-t border-[#ddd9d1] max-w-sm font-mono"><div><span className="block text-xl font-black text-black">{projects.length}</span><span className="text-[10px] text-[#8a8a8a] uppercase font-semibold">Projects</span></div><div><span className="block text-xl font-black text-black">{skills.length}</span><span className="text-[10px] text-[#8a8a8a] uppercase font-semibold">Skills</span></div></div>',
  '        </div>',
  '        <div className="md:col-span-5 flex justify-center items-center">',
  '          <div className="relative w-64 h-64">',
  '            <div className="absolute inset-[-6px] rounded-2xl border-2 border-[#ddd9d1]"></div>',
  '            <div className="w-full h-full rounded-2xl overflow-hidden border border-[#ddd9d1] bg-[#f0ede8]">{personalInfo.avatarUrl ? <img src={personalInfo.avatarUrl} className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center text-4xl font-black text-[#8a8a8a]">{initials}</div>}</div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '    <section id="about" className="py-24 bg-[#f8f7f4] border-t border-[#ddd9d1]">',
  '      <div className="max-w-5xl mx-auto px-6"><div className="mb-12"><span className="font-mono text-xs uppercase tracking-widest vp-accent-text">// about me</span><h2 className="text-2xl font-extrabold text-black">Who I Am</h2></div>',
  '        <div className="grid grid-cols-1 md:grid-cols-2 gap-12"><div className="space-y-4 text-sm text-[#4a4a4a]"><p>{personalInfo.bio}</p><p>Location: {personalInfo.location}</p><p>Email: {personalInfo.email}</p></div>',
  '          <div className="space-y-4"><h3 className="text-sm font-bold text-black uppercase tracking-wider">Education</h3>{education.map((edu, idx) => (<div key={idx} className="vp-card p-4 flex gap-4 items-center"><div className="w-10 h-10 bg-[#f5e8e3] text-[#c8502a] rounded-lg flex items-center justify-center shrink-0"><GraduationCap size={18} /></div><div className="text-xs"><h4 className="font-bold text-[#1a1a1a]">{edu.degree}</h4><p className="text-[#8a8a8a]">{edu.college} ({edu.year})</p></div></div>))}</div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '    <section id="experience" className="py-24 bg-white border-t border-[#ddd9d1]">',
  '      <div className="max-w-4xl mx-auto px-6"><div className="mb-12"><span className="font-mono text-xs uppercase tracking-widest vp-accent-text">// experience</span><h2 className="text-2xl font-extrabold text-black">Work History</h2></div>',
  '        <div className="vp-timeline relative space-y-8">{experience.map((exp, idx) => (<div key={idx} className="relative pl-10"><span className="absolute left-[7px] top-6 w-4 h-4 rounded-full border-[3px] border-white bg-[#c8502a]"></span><div className="vp-card p-5 space-y-2"><div className="flex justify-between items-center"><h3 className="text-sm font-bold text-[#1a1a1a]">{exp.role}</h3><span className="text-[10px] font-mono font-bold vp-accent-text">{exp.duration}</span></div><h4 className="text-xs text-[#8a8a8a]">{exp.company}</h4><p className="text-xs text-[#4a4a4a] leading-relaxed">{exp.description}</p></div></div>))}</div>',
  '      </div>',
  '    </section>',
  '    <section id="projects" className="py-24 bg-[#f8f7f4] border-t border-[#ddd9d1]">',
  '      <div className="max-w-5xl mx-auto px-6"><div className="mb-12"><span className="font-mono text-xs uppercase tracking-widest vp-accent-text">// projects</span><h2 className="text-2xl font-extrabold text-black">Featured Projects</h2></div>',
  '        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">{projects.map((proj, idx) => (<div key={idx} className="vp-card p-6 flex flex-col justify-between relative overflow-hidden vp-project-card"><div className="space-y-4"><div className="flex justify-between items-center"><div className="w-10 h-10 bg-[#f5e8e3] text-[#c8502a] rounded-lg flex items-center justify-center"><Code size={18} /></div></div><div><h3 className="text-sm font-bold text-black uppercase">{proj.title}</h3><p className="text-xs text-[#4a4a4a] mt-2">{proj.description}</p></div></div><div className="mt-4 pt-3 border-t border-[#f0ede8] flex flex-wrap gap-1">{proj.technologies.map((t, idx2) => (<span key={idx2} className="text-[9px] font-mono bg-[#f0ede8] border text-[#4a4a4a] px-2 py-0.5 rounded">{t}</span>))}</div></div>))}</div>',
  '      </div>',
  '    </section>',
  '    <footer className="bg-[#1a1a1a] py-8 text-center text-xs text-[#8a8a8a]"><p>Designed & Built by <span className="vp-accent-text font-bold">{personalInfo.fullName}</span> &copy; {new Date().getFullYear()}</p></footer>',
  '  </div>',
  ');',
].join('\n');

const DEFAULT_RENDERER = [
  'return (',
  '  <div className="max-w-3xl mx-auto px-6 py-20 space-y-12" style={{backgroundColor: \'var(--bg)\'}}>',
  '    <header className="space-y-4">',
  "      <h1 className=\"text-4xl font-extrabold text-white\">{personalInfo.fullName || 'Professional'}</h1>",
  '      <p className="text-sm font-semibold" style={{color: \'var(--primary)\'}}>{personalInfo.location}</p>',
  '      <p className="text-xs text-gray-400">{personalInfo.bio}</p>',
  '    </header>',
  '    <main className="space-y-8">',
  '      <section className="space-y-2">',
  '        <h2 className="text-lg font-bold border-b pb-2 text-white">Capabilities</h2>',
  '        <div className="flex flex-wrap gap-2">{skills.map((s, idx) => (<span key={idx} className="text-xs px-3 py-1 bg-white/5 border border-white/10 rounded-full">{s.name}</span>))}</div>',
  '      </section>',
  '      <section className="space-y-4">',
  '        <h2 className="text-lg font-bold border-b pb-2 text-white">Selected Works</h2>',
  '        {projects.map((p, idx) => (<div key={idx} className="p-4 border border-white/5 bg-white/[0.01]"><h3 className="text-sm font-bold text-white">{p.title}</h3><p className="text-xs text-gray-400 mt-1">{p.description}</p>{p.liveLink && <a href={p.liveLink} className="text-xs hover:underline mt-2 inline-block" style={{color: \'var(--primary)\'}}>Demo</a>}</div>))}',
  '      </section>',
  '    </main>',
  '  </div>',
  ');',
].join('\n');

export function getRendererCode(id: string): string {
  switch (id) {
    case 'codecraft':
      return CODECRAFT_RENDERER;
    case 'devhub':
      return DEVHUB_RENDERER;
    case 'viveportfolio':
      return VIVEPORTFOLIO_RENDERER;
    default:
      return DEFAULT_RENDERER;
  }
}
